export const deskArray = [
   'Arts',
   'Adventure Sports',
   'Books',
   'Business Day',
   'Cars',
   'Culture',
   'Crosswords & Games',
   'Escapes',
   'Games',
   'Fashion',
   'Food',
   'Fashion & Style',
   'Flight',
   'Generations',
   'Giving',
   'Home',
   'Health',
   'Home & Garden',
   'Jobs',
   'Movies',
   'Media',
   'National',
   'Nesting',
   'Personal Investing',
   'Play',
   'Politics',
   'Science',
   'Sports',
   'Style',
   'Theater',
   'Thursday Styles',
   'Times Topics',
   'Travel',
   'Upshot',
   'Universal',
   'Vacation',
   'Weather',
   'Week',
   'Westchester',
   'World',
   'Your Money',
];
